# scp -P 4422 -r /github/raphael/github-webhook rguzman@192.168.1.179:/home/rguzman/Documents/docker-compose/cards-webhook
version: '2.4'
services:
  ngrok:
    build:
      context: ./ngrok
    image: raphaelguzman/ngrok:v1.0
    environment:
      - NGROK_TOKEN
      - GITHUB_TOKEN
    networks:
      - main
  hook:
    build:
      context: ./hook
    image: raphaelguzman/github-webhook:v1.0
    environment:
      - GITHUB_TOKEN
    networks:
      - main
    depends_on:
      ngrok:
        condition: service_healthy
networks:
  main:
      